name: Deploy to AWS

on:
  workflow_run:
    workflows:
      - Build and Push Docker Images to dockerhub
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH keys
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Deploy RestApi_Address to EC2 Instance 1
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@ec2-34-235-117-254.compute-1.amazonaws.com << 'EOF'
            if ! command -v docker &> /dev/null
            then
              sudo dnf install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
            fi
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/restapi_address:latest
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm -f $(sudo docker ps -aq) || true
            sudo docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/restapi_address:latest
          EOF

      - name: Deploy RestApi_RyM to EC2 Instance 2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@ec2-54-197-164-35.compute-1.amazonaws.com << 'EOF'
            if ! command -v docker &> /dev/null
            then
              sudo dnf install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
            fi
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/restapi_rym:latest
            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm -f $(sudo docker ps -aq) || true
            sudo docker run -d -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/restapi_rym:latest
          EOF
