name: Build and Push Docker Images to dockerhub

on:
    push:
        branches:
            - feature/qa-integration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build RestApi_Address Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/restapi_address:latest ./RestApi_Address
    
      - name: Push RestApi_Address Docker image
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/restapi_address:latest

      - name: Build RestApi_RyM Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/restapi_rym:latest ./RestApi_RyM

      - name: Push RestApi_RyM Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/restapi_rym:latest